name: IDX Scraper Cron Job

on:
  workflow_dispatch:

  schedule:
    - cron: '0 15 * * *'

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Chrome dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run Scraper
        env:
          GEMINI_APP_KEY: ${{ secrets.GEMINI_APP_KEY }}
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_API_SECRET: ${{ secrets.MAILJET_API_SECRET }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: node dist/scraper.js

      - name: Upload error artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-artifacts
          path: |
            error_screenshot.png
            error_page.html