name: IDX Scraper Cron Job

on:
  workflow_dispatch:

  schedule:
    - cron: '0 15 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run the scraper
        run: |
          docker build -t idx-scraper .
          docker run --rm \
            -e GEMINI_APP_KEY="${{ secrets.GEMINI_APP_KEY }}" \
            -e MAILJET_API_KEY="${{ secrets.MAILJET_API_KEY }}" \
            -e MAILJET_API_SECRET="${{ secrets.MAILJET_API_SECRET }}" \
            -e SENDER_EMAIL="${{ secrets.SENDER_EMAIL }}" \
            -e RECIPIENT_EMAIL="${{ secrets.RECIPIENT_EMAIL }}" \
            idx-scraper